<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>
    <LangVersion>Latest</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Anton Heryanto Hasan</Authors>
	<PackageId>Seismic</PackageId>
    <Version>0.9.5</Version>
    <Copyright>2026</Copyright>
    <Description>High performance seismic reader</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NativeMemoryArray" Version="1.2.2" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.1" />
	<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.1" />
  </ItemGroup>

</Project>
