<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <LangVersion>Latest</LangVersion>
    <NullableReferenceTypes>true</NullableReferenceTypes>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Anton Heryanto Hasan</Authors>
    <Version>0.4.1</Version>
    <Copyright>2022</Copyright>
    <Description>High performance seismic reader</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Version="7.0.0" />
	<PackageReference Include="System.Text.Encoding.CodePages" Version="4.7.0" />
  </ItemGroup>

</Project>
